MatchTacticType = { 0 :	"Normal",
                    1 :	"Pressing",
                    2 : "Counter-attacks",
                    3 : "Attack in the middle",
                    4 : "Attack in wings",
                    7 : "Play creatively",
                    8 :	"Long shots" }
MatchTeamAttitude = { -1 :	"Play it cool",
                       0 :	"Normal",
                       1 :  "Match of the season" }
PlayerCategoryID = { 0	: "No category set",
                     1	: "Keeper",
                     2	: "Wing back",
                     3	: "Central defender",
                     4  : "Winger",
                     5	: "Inner midfielder",
                     6  : "Forward",
                     7	: "Substitute",
                     8  : "Reserve",
                     9  : "Extra 1",
                    10  : "Extra 2" }
SpecialtyID =     {  0	: "No specialty",
                     1  : "Technical",
                     2	: "Quick",
                     3  : "Powerful",
                     4  : "Unpredictable",
                     5  : "Head specialist",
                     6	: "resilient",
                     8  : "support" }
TeamSpiritID =    {  10	: "Paradise on Earth!",
                     9	: "walking on clouds",
                     8	: "delirious",
                     7  : "satisfied",
                     6  : "content",
                     5  : "calm",
                     4	: "composed",
                     3  : "irritated",
                     2  : "furious",
                     1  : "murderous",
                     0	: "like the Cold War" }
trainingType =    {  0	: "General (Deprecated)",
                     1	: "Stamina (Deprecated)",
                     2	: "Set Pieces",
                     3	: "Defending",
                     4  : "Scoring",
                     5  : "Cross Pass (Winger)",
                     6  : "Shooting",
                     7  : "Short Passes",
                     8  : "Playmaking",
                     9	: "Goaltending",
                    10  : "Through Passes",
                    11  : "Defensive Positions",
                    12	: "Wing Attacks" }


